version: 2

models:
  - name: dim_products
    description: Marts model describe product entity
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: description
        tests:
          - not_null