version: 2

models:
  - name: stg_orders
    description: Cleaned staging view for raw orders.
    columns:
      - name: invoice_no
        tests:
          - not_null
      - name: stock_code
        tests:
          - not_null
      - name: description
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null
      - name: invoice_date
        tests:
          - not_null
      - name: customer_id
      - name: country